### ISSUE TITLE
Cocoapods Support

### ISSUE THREAD

**Issue by mitchtreece** [async-plus/async-plus#12]
Thanks for the work! Nice little QoL improvements for those of us embracing Swift's native async/await implementation 🙌🏻

However, a lot of us are still (at least partially) still using Cocoapods for dependency management. In an ideal world, we would just use SPM for everything - but there are a lot of libraries that either:

1. Don't support it at all yet
2. Support it, but lose some required features that Cocoapods provides (i.e. subspecs)

Could you integrate this project with pods so all the rest of us can easily import it? 😄

**Comment by montaguegabe** [comment]
Yes! I am planning to integrate cocoa pods soon along with a V2 release with `get`

**Comment by montaguegabe** [comment]
@mitchtreece All set!  Version 1.1.1 is available as a Cocoapod now (#13)

Thanks very much and please feel free to share other feedback with this library here in Issues
